services:
  mysql:
    image: mysql:5.7
    container_name: domainmonitor
    restart: always
    environment:
      MYSQL_DATABASE: 'domainmonitor'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3334:3306'
    volumes:
      - mysql:/var/lib/mysql
# Names our volume
volumes:
  mysql:
